permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Zach Holman
url: https://hackfestcc.github.io/manual-hacker
description: Manual do Hackfest contra Corrupção.
twitter: hackfestbrasil
