permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Manual do Hackathon
url: https://hackathon-sbrc2018.github.io/manual-hacker
description: Manual do Hackathon SBRC 2018
twitter: sbrc2018
